outbound_access_host: bidrag-sjablon.dev-fss-pub.nais.io
ingresses:
  - https://bidragskalkulator-api.intern.dev.nav.no

BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon

SPRING_PROFILES_ACTIVE: dev