ingresses:
  - https://bidragskalkulator-api.intern.dev.nav.no

env:
  SPRING_PROFILES_ACTIVE: dev
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon
  BIDRAG_PERSON_URL: https://bidrag-person-q1.dev-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: dev-fss.bidrag.bidrag-person-q1
  BIDRAG_GRUNNLAG_URL: https://bidrag-grunnlag.intern.dev.nav.no
  BIDRAG_GRUNNLAG_SCOPE: dev-gcp.bidrag.bidrag-grunnlag
  KODEVERK_URL: https://kodeverk.dev-fss-pub.nais.io
  NAIS_APP_NAME: bidrag-bidragskalkulator-api
  FOERSTESIDE_GENERATOR_SCOPE: dev-fss.teamdokumenthandtering.foerstesidegenerator-q1
  FOERSTESIDE_GENERATOR_URL: https://foerstesidegenerator-q1.dev.intern.nav.no
  BIDRAG_DOKUMENTPRODUKSJON_URL: https://bidrag-dokument-produksjon.intern.dev.nav.no

inbound_application:
  - application: bidrag-bidragskalkulator-v2
    namespace: bidrag
    cluster: dev-gcp
  - application: tokenx-token-generator
    namespace: nais
    cluster: dev-gcp
outbound_external_host:
  - bidrag-sjablon.dev-fss-pub.nais.io
  - bidrag-grunnlag.intern.dev.nav.no
  - bidrag-person-q1.dev-fss-pub.nais.io
