apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  name: bidrag-bidragskalkulator-api
  namespace: bidrag
  labels:
      team: bidrag

spec:
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  image: {{ image }}
  port: 8080
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
  env:
    - name: BIDRAG_SJABLON_URL
      value: {{BIDRAG_SJABLON_URL}}
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: bidrag-bidragskalkulator-v2
          namespace: bidrag
    outbound:
      external:
        - host: {{outbound_access_host}}
  liveness:
    path: /api/internal/isalive
    initialDelay: 15
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /api/internal/isready
    initialDelay: 15
    timeout: 1