ingresses:
  - https://bidragskalkulator-api.intern.nav.no

env:
  SPRING_PROFILES_ACTIVE: prod
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_GRUNNLAG_URL: https://bidrag-grunnlag.intern.nav.no
  BIDRAG_GRUNNLAG_SCOPE: prod-gcp.bidrag.bidrag-grunnlag
  KODEVERK_URL: https://kodeverk.prod-fss-pub.nais.io
  NAIS_APP_NAME: bidrag-bidragskalkulator-api
  VEDTAK_KAFKA_TOPIC: bidrag.vedtak
  VEDTAK_KAFKA_GROUP_ID: bidrag-bidragskalkulator-api

kafka:
  pool: nav-dev

inbound_application:
  - application: bidrag-bidragskalkulator-v2
    namespace: bidrag
    cluster: prod-gcp
outbound_external_host:
  - bidrag-sjablon.prod-fss-pub.nais.io
  - bidrag-person.prod-fss-pub.nais.io