ingresses:
  - https://bidragskalkulator-api.intern.nav.no

env:
  SPRING_PROFILES_ACTIVE: prod
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  BIDRAG_PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  BIDRAG_PERSON_SCOPE: prod-fss.bidrag.bidrag-person
inbound_application:
  - application: bidrag-bidragskalkulator-v2
    namespace: bidrag
    cluster: prod-gcp
outbound_external_host:
  - bidrag-sjablon.prod-fss-pub.nais.io
  - bidrag-person.prod-fss-pub.nais.io