springdoc:
  packages-to-scan: no.nav.bidrag.behandling.controller
  paths-to-match: "/api/**"
  swagger-ui:
    path: /
    showCommonExtensions: true

spring.config.activate.on-profile: local, test
BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon
