springdoc:
  packages-to-scan: no.nav.bidrag.bidragskalkulator.controller
  paths-to-match: "/api/**"
  swagger-ui:
    path: /
    showCommonExtensions: true

spring.config.activate.on-profile: local
BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon

---
spring.config.activate.on-profile: local-nais
BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon

no.nav.security.jwt:
  issuer:
    tokenx:
      discovery_url: https://tokenx.dev-gcp.nav.cloud.nais.io/.well-known/oauth-authorization-server
      accepted_audience: dev-gcp:bidrag:bidrag-bidragskalkulator-api-feature

