springdoc:
  packages-to-scan: no.nav.bidrag.bidragskalkulator.controller
  paths-to-match: "/api/**"
  swagger-ui:
    path: /
    showCommonExtensions: true

logging.level:
  secureLogger: DEBUG

spring:
  main:
    banner-mode: off
  cache:
    cache-names: underholdskostnad,personinformasjon
    caffeine:
      spec: maximumSize=500,expireAfterWrite=1h

spring.config.activate.on-profile: local
BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon
BIDRAG_GRUNNLAG_URL: https://bidrag-grunnlag.intern.dev.nav.no

kafka:
  bootstrapServers: localhost:9092
  consumerGroupId: bidrag-bidragskalkulator-api-local
  listenerTopic: bidrag-listener-topic
  producerTopic: bidrag-microfrontend-topic

bidrag:
  grunnlag:
    url: ${BIDRAG_GRUNNLAG_URL}
    hentGrunnlagPath: hentgrunnlag

---
spring.config.activate.on-profile: prod, dev, local-nais

kafka:
  bootstrapServers: ${KAFKA_BROKERS}
  consumerGroupId: ${KAFKA_CONSUMER_GROUP_ID:bidrag-bidragskalkulator-api}
  listenerTopic: ${KAFKA_LISTENER_TOPIC:bidrag-listener-topic}
  producerTopic: ${KAFKA_PRODUCER_TOPIC:bidrag-microfrontend-topic}

saf:
  selvbetjening:
    url: ${SAFSELVBETJENING_URL}

foerstesidegenerator:
  url: ${FOERSTESIDE_GENERATOR_URL:https://foerstesidegenerator-q1.dev.intern.nav.no}
  genererFoerstesidePath: /api/foerstesidegenerator/v1/foersteside

bidrag:
  dokumentproduksjon:
    genererPdfPath: /api/dokument/pdf/test/bidragskalkulator/privatavtale
    url: ${BIDRAG_DOKUMENTPRODUKSJON_URL}
  grunnlag:
    url: ${BIDRAG_GRUNNLAG_URL}
    hentGrunnlagPath: hentgrunnlag
  person:
    url: ${BIDRAG_PERSON_URL}
    hentMotpartbarnrelasjonPath: motpartbarnrelasjon
    hentPersoninformasjonPath: informasjon

no.nav.security.jwt:
  client:
    registration:
      safselvbetjening:
        resource-url: ${SAFSELVBETJENING_URL}
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        token-x-url: ${TOKEN_X_TOKEN_ENDPOINT}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        scope: api://${SAFSELVBETJENING_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
        authentication-token-x:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
          client-auth-method: private_key_jwt
      foerstesidegenerator:
        resource-url: ${FOERSTESIDE_GENERATOR_URL}
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${FOERSTESIDE_GENERATOR_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
        authentication-token-x:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
          client-auth-method: private_key_jwt
      bidrag-person:
        resource-url: ${BIDRAG_PERSON_URL}
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        token-x-url: ${TOKEN_X_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${BIDRAG_PERSON_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
        authentication-token-x:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
          client-auth-method: private_key_jwt
      bidrag-grunnlag:
        resource-url: ${BIDRAG_GRUNNLAG_URL}
        token-endpoint-url: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token
        token-x-url: ${TOKEN_X_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${BIDRAG_GRUNNLAG_SCOPE}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
        authentication-token-x:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
          client-auth-method: private_key_jwt
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
