springdoc:
  packages-to-scan: no.nav.bidrag.bidragskalkulator.controller
  paths-to-match: "/api/**"
  swagger-ui:
    path: /
    showCommonExtensions: true

spring.main.banner-mode: off

spring.config.activate.on-profile: local
BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon

---
spring.config.activate.on-profile: prod, dev, local-nais
BIDRAG_SJABLON_URL: ${BIDRAG_SJABLON_URL}

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
