name: Verify Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew test --no-daemon --stacktrace
        env:
          SPRING_PROFILES_ACTIVE: test
          BIDRAG_SJABLON_URL: https://bidrag-sjablon.dev-fss-pub.nais.io/bidrag-sjablon